name: Deploy to ECR

on:
 
  push:
    branches: [ master ]
permissions:
  id-token: write
  contents: read

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

   
    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          role-to-assume: arn:aws:iam::489994096722:role/saad-ecr-role
          aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build
      env:
        ECR_REPOSITORY: saad
      run: |
        docker build -t saad .
        
    - name: Tag and Push
      env:
        ECR_REPOSITORY: saad
      run: |
        docker tag saad:latest 489994096722.dkr.ecr.us-east-1.amazonaws.com/saad:latest
        docker push 489994096722.dkr.ecr.us-east-1.amazonaws.com/saad:latest
